apps:
  - name: App
    script: ./index.js
    exec_mode: cluster
    instances: 2
    watch: false
    max_memory_restart: '200M'

/* desenvolvido na war room esquci o nome do cidadão que me guiou :( */