apps:
  - name: strangers things
    script: ./index.js
    exec_mode: cluster
    instances: 2
    watch: false
    max_memory_restart: 200M
    env_hawkins:
      UPSIDEDOWN_MODE: false
    env_upside-down:
      UPSIDEDOWN_MODE: true