apps:
  - name: app
    script: ./index.js
    exec_mode: cluster
    instances: 2
    watch: false
    max-memory-restart: 20M
    hawkins:
      UPSIDEDOWN_MODE: false
    upside-down:
      UPSIDEDOWN_MODE: true
