apps:
  - name: 'hawkings'
    script: './index.js'
    exec_mode: 'cluster'
    instances: 2
    max_memory_restart: '200M'
    env_prod:
      PORT: 3000
      UPSIDEDOWN_MODE: false
    env_homolog:
      PORT: 3000
      UPSIDEDOWN_MODE: false
  - name: 'upside-down'
    script: './index.js'
    exec_mode: 'cluster'
    instances: 2
    max_memory_restart: '200M'
    env_prod:
      PORT: 3000
      UPSIDEDOWN_MODE: true
    env_homolog:
      PORT: 3000
      UPSIDEDOWN_MODE: true